require('dotenv').config()

/*Docusign constant variables*/
const DOCUSIGN_CLIENT_ID = process.env.DOCUSIGN_CLIENT_ID;
const DOCUSIGN_USER_ID = process.env.DOCUSIGN_USER_ID;
const DOCUSIGN_INSTANCE_URI = process.env.DOCUSIGN_INSTANCE_URI;
const DOCUSIGN_SCOPE = process.env.DOCUSIGN_SCOPE;
const DOCUSIGN_ACCOUNT_ID = process.env.DOCUSIGN_ACCOUNT_ID;
const DOCUSIGN_BASE_PATH = process.env.DOCUSIGN_BASE_PATH;
const DOCUSIGN_CC_EMAIL = process.env.DOCUSIGN_CC_EMAIL;
const DOCUSIGN_CC_NAME = process.env.DOCUSIGN_CC_NAME;
const DOCUSIGN_WEBHOOK_BASEURL = process.env.DOCUSIGN_WEBHOOK_BASEURL;


module.exports = {DOCUSIGN_CLIENT_ID, DOCUSIGN_USER_ID, DOCUSIGN_INSTANCE_URI, DOCUSIGN_SCOPE, DOCUSIGN_ACCOUNT_ID, DOCUSIGN_BASE_PATH, DOCUSIGN_CC_EMAIL, DOCUSIGN_CC_NAME, DOCUSIGN_WEBHOOK_BASEURL}